# Generated by Django 4.2.4 on 2023-08-09 15:34

from django.db import migrations
import phonenumber_field.modelfields
import phonenumber_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, validators=[phonenumber_field.validators.validate_international_phonenumber]),
        ),
    ]
